#pragma once

// ============================================================================
// AUTO-GENERATED by calibrate_engine.py -- DO NOT EDIT BY HAND.
// Regenerate with: python calibrate_engine.py
//
// Generated : 2026-09-19T14:09:53
// Dataset   : historical_games.csv (1225 real games)
// Model     : actual_margin ~ intercept + b_rest*rest_advantage + b_def*net_def_edge
//             (OLS; intercept = home-court effect -- see this script's module
//             docstring for why home-court is estimated via the intercept
//             rather than a regressor, given this dataset's all-team_a-home
//             structure)
// R^2       : 0.186
//
//   Term                       Coefficient   Std.Error   t-stat   Significant?
//   intercept (home-court)         +1.6143      0.4088     3.95   yes
//   rest_advantage                 +1.1839      0.4258     2.78   yes
//   net_def_edge                   +1.5466      0.0938    16.49   yes
//
// A coefficient marked "NO" above is not statistically distinguishable from
// zero at this sample size. It is still included below at its fitted,
// honest magnitude rather than zeroed out or replaced with a guess -- but
// should not be read as a proven real-world effect. Re-run
// `calibrate_engine.py` against more games for a sturdier estimate.
//
// Included by both cpp_engine/cuda_simulator.cu and cpp_engine/main.cpp, so
// the GPU batch engine and CPU narrative engine always share one calibration.
// ============================================================================

namespace engine_calibration {

// Shot-probability shift per net_def_edge point (team_b.def_rating -
// team_a.def_rating). Always applied intrinsically -- every roster carries
// its own real def_rating (see GPURoster::def_rating / Team::def_rating),
// no external flag required.
constexpr double kDefResistanceProbPerRating = 0.00336223;

// Shot-probability shift per day of REST ADVANTAGE (fit as the
// rest_advantage regression coefficient, positive = more rest is better).
// A team on a back-to-back (0 rest days) has roughly -1 unit of rest
// advantage relative to a normally-rested opponent, so the engine must
// apply it as -kFatigueProbPerRestDay (a penalty), not add it directly --
// requires the --b2b-a/--b2b-b flag, since "is this team on a
// back-to-back" is game-context information no roster stat can supply.
constexpr double kFatigueProbPerRestDay = 0.00257367;

// Shot-probability shift applied to the home team -- requires the
// --home-a/--home-b flag for the same reason as fatigue above (venue is
// game context, not a roster property).
constexpr double kHomeCourtProbShift = 0.00350926;

}  // namespace engine_calibration
